# Generated by Django 3.2 on 2021-04-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posto',
            new_name='Post',
        ),
    ]
